version: '3.1'

services:
  app:
    build:
      context: .
    ports: 
      - 8000:4000
    depends_on: 
      - postgres
    volumes:
      - .:/home
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .:/aluraflix-backend